# Stages
FIRST, FOURTH, SEVENTH = range(3)
# Handlers da linguagem
PYTHON, FUNCAO_PYTHON, CLASS_PYTHON, CONTROLE_PYTHON, ARRAYS_PYTHON, OPER_EXP_PYTHON, PYTHON = range(7)
# call_backs
VOLTA_PYTHON, VOLTA_ARRAY, VOLTA_EST_CONTROLE, VOLTA_OPER, LISTA_PYTHON, DIC_PYTHON, TUPLA_PYTHON, IF_PYTHON, FOR_PYTHON, TRY_PYTHON, COMP_PYTHON, LOG_PYTHON, IDENT_PYTHON, ARIT_PYTHON = range(14)